### ISSUE TITLE
pdftk hangs

### ISSUE THREAD

**Issue by ghazel** [jottr/alpine-pdftk#1]
This `pdftk` hangs on simple things like:

```
$ wget https://www.irs.gov/pub/irs-pdf/fw4.pdf
$ pdftk fw4.pdf output foo.pdf owner_pw 12345
```

**Comment by ghazel** [comment]
This command is incorrect, which prints an error message on the 2.02 version for macOS.

Still, it probably shouldn't hang indefinitely.

**Comment by jottr** [comment]
Works for me on `2.02`.
