### ISSUE TITLE
: Service 'pdftk' failed to build:

### ISSUE THREAD

**Issue by grekpg** [jottr/alpine-pdftk#2]
Step 1/4 : FROM alpine:edge
edge: Pulling from library/alpine
2004ee2154b4: Pull complete
Digest: sha256:db9c935c5445f75cace46d0418fac19d0b70b1723193e3b47d0d06bcddd05272
Status: Downloaded newer image for alpine:edge
 ---> 43cffc6f84a4
Step 2/4 : MAINTAINER github.com/jottr
 ---> Running in 610920b62344
Removing intermediate container 610920b62344
 ---> ba82b45fc874
Step 3/4 : RUN apk update && apk upgrade       && apk add pdftk
 ---> Running in 555ac6cf5fa7
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
v20190508-1284-g24cebe87e2 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v20190508-1271-g9f9fe1a1de [http://dl-cdn.alpinelinux.org/alpine/edge/community]
OK: 10162 distinct packages available
(1/3) Upgrading alpine-baselayout (3.1.1-r0 -> 3.1.1-r1)
Executing alpine-baselayout-3.1.1-r1.pre-upgrade
Executing alpine-baselayout-3.1.1-r1.post-upgrade
(2/3) Upgrading libcrypto1.1 (1.1.1b-r1 -> 1.1.1c-r0)
(3/3) Upgrading libssl1.1 (1.1.1b-r1 -> 1.1.1c-r0)
Executing busybox-1.30.1-r1.trigger
OK: 6 MiB in 14 packages
ERROR: unsatisfiable constraints:
  so:libgcj.so.17 (missing):
    required by: pdftk-2.02-r1[so:libgcj.so.17]
ERROR: Service 'pdftk' failed to build: The command '/bin/sh -c apk update && apk upgrade       && apk add pdftk' returned a non-zero code: 2

**Comment by jottr** [comment]
This is due to: https://bugs.alpinelinux.org/issues/10136
